version: "3.9"

#Para axeder al contenedor es con el comando docker exec -it nombre_contenedor bash

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PRONIM
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    # networks define la red que se va a utilizar, por lo que si hay 2 servicios que se van a comunicar, deben estar en la misma red
    networks:
      - mern_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_server
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: PRONIM
      DB_PORT: 3306
      PORT: 3001
    depends_on:
      - db
    # networks define la red que se va a utilizar, por lo que si hay 2 servicios que se van a comunicar, deben estar en la misma red
    networks:
      - mern_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # networks define la red que se va a utilizar, por lo que si hay 2 servicios que se van a comunicar, deben estar en la misma red
    networks:
      - mern_network

volumes:
  db_data:

networks:
  mern_network:
