version: "3.9"

#Para axeder al contenedor es con el comando docker exec -it nombre_contenedor bash

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PRONIM
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mern_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend_dev
    command: ["nodemon", "index.js"]
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: PRONIM
      DB_PORT: 3306
      PORT: 3001
    # depends_on: indica que este servicio depende de otro, por lo que se va a esperar a que el servicio db esté listo para poder iniciar
    depends_on:
      - db
    networks:
      - mern_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend_dev
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    # depends_on: indica que este servicio depende de otro, por lo que se va a esperar a que el servicio backend esté listo para poder iniciar
    depends_on:
      - backend
    networks:
      - mern_network

# volumes: se define el volumen que se va a utilizar para almacenar los datos de la base de datos
volumes:
  db_data:

networks:
  mern_network:
