# Usar Node.js para desarrollo
FROM node:22.9.0

WORKDIR /app

# Copiar dependencias y Nodemon para desarrollo
COPY package*.json ./
RUN npm install --save-dev nodemon

COPY . .

EXPOSE 3001

# Comando para desarrollo con Nodemon
CMD ["npx", "nodemon", "index.js"]
